version: "3.1"
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    tty: true
    ports:
    - 8383:80
    volumes:
    - "./frontend:/app"
    depends_on:
      - backend
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    tty: true
    ports:
    - 8181:8000
    volumes:
      - "./backend:/app"
      - "./config/php:/usr/local/etc/php"
      - "/var/lib/docker/containers:/containersData"
    depends_on:
      - database
  database:
    image: mysql:5.7
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker_db
    volumes:
    - /var/lib/mysql
