version: "3.1"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    command: sh -c "npm install && npm run dev"
    volumes:
    - "/var/www/docker-project/frontend:/app"
    depends_on:
      - backend
    environment:
      HOST: 0.0.0.0
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
    - 8181:8181
    volumes:
      - "/var/www/docker-project/backend:/app"
      - "/var/www/docker-project/config/php:/usr/local/etc/php"
      - "/var/lib/docker/containers:/containersData"
    depends_on:
      - database
  database:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 770770
      MYSQL_DATABASE: docker_db
    volumes:
    - /var/lib/mysql
